WICG/client-hints-infrastructure

index.bs

Markdown/bikeshed formatting things, mostly.

Nits and formatting

---

index.bs

...which has been removed from the IETF spec

Remove bullet about Accept-CH-Lifetime

---

index.bs

A handful of little errors, fixed

Little things

---

index.bs

Registry revamp

---

README.md

Update the explainer

---

README.md

This is a tiny fix for a typo 😄

fix a missing close paren

---

index.bs

Accompanying PR to https://github.com/WICG/ua-client-hints/pull/38

Add UA- prefix for UA hints

---

index.bs

Fixes https://github.com/WICG/client-hints-infrastructure/issues/19#issuecomment-642391120

Fix FP defaults for ua and ua-mobile

---

reliability.md

Add an explainer for a Client Hint reliability mechanism.

---

reliability.md

Also fix a typo in a section link.

Add links to draft-davidben-http-client-hint-reliability

---

reliability.md

Talk about DNS in the alternatives section for reliability.

---

README.md
index.bs

Fixes #53 - Update references to point to RFC8942

---

index.bs

PTAL @yoavweiss (open to wording suggestions, not sure the second sentence is that useful)

Fixes #55 - Add Note to clarify how to clear Accept-CH cache.

---

reliability.md

Update one more reference to RFC8942.

---

index.bs

This is the infra half to https://github.com/WICG/ua-client-hints/pull/210
(And apparently we forgot to add UA-Platform-Version 🙈 )

Fixes #59 - Add a UA-Bitness hint

---

deploy.sh
index.bs

(also drive-by fix for the out of date deploy script)
PTAL @yoavweiss

Fixes #61 - export "client hints token" dfn

---

index.bs

Fixes #65 - Add Sec-CH-UA-Platform to low entropy hint table

---

.travis.yml
index.bs

Fixes #64 - Add missing UA-Full-Version

---

index.bs

Fix conflicting save-data naming

---

.pr-preview.json

This will make catching drafting errors a lot simpler.
https://github.com/WICG/ua-client-hints/pull/71
https://github.com/apps/pr-preview

Add PR preview

---

index.bs

PTAL @yoavweiss
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/84.html" title="Last updated on Aug 31, 2021, 1:24 PM UTC (c1fa731)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/84/8cba795...miketaylr:c1fa731.html" title="Last updated on Aug 31, 2021, 1:24 PM UTC (c1fa731)">Diff</a>

Fixes #71 - Fix allowlist for sec-ua-platform

---

index.bs

closes #75
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/92.html" title="Last updated on Jan 19, 2022, 5:07 PM UTC (78042dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/92/623a124...78042dc.html" title="Last updated on Jan 19, 2022, 5:07 PM UTC (78042dc)">Diff</a>

Consider Accept-CH Cache to be partitioned

---

index.bs

Let's make the formatting consistent and resolve any outstanding compiler issues/warnings.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/97.html" title="Last updated on Feb 2, 2022, 12:01 AM UTC (44a68b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/97/fb0a799...44a68b2.html" title="Last updated on Feb 2, 2022, 12:01 AM UTC (44a68b2)">Diff</a>

Fix formatting and compilation

---

index.bs

PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/104.html" title="Last updated on Apr 8, 2022, 11:50 PM UTC (6c44725)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/104/63db401...miketaylr:6c44725.html" title="Last updated on Apr 8, 2022, 11:50 PM UTC (6c44725)">Diff</a>

Editorial: simplify check for non-secure contexts

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/117.html" title="Last updated on Jun 29, 2022, 5:17 AM UTC (c1a625b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/117/5c39d3a...c1a625b.html" title="Last updated on Jun 29, 2022, 5:17 AM UTC (c1a625b)">Diff</a>

Fix up markup errors

---

README.md

Update README to reflect HTML tag

---

index.bs

We don't need to include the full implementation details,
but we should have enough to make it clear where the
integration point is and where more can be learned.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/136.html" title="Last updated on Dec 22, 2022, 1:34 PM UTC (779562d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/136/a29d99b...779562d.html" title="Last updated on Dec 22, 2022, 1:34 PM UTC (779562d)">Diff</a>

Integrate ACCEPT_CH frame

---

index.bs

This is required by https://github.com/w3c/webappsec-clear-site-data/pull/74/
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/156.html" title="Last updated on Jun 28, 2023, 3:30 PM UTC (3f89c17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/156/193d599...3f89c17.html" title="Last updated on Jun 28, 2023, 3:30 PM UTC (3f89c17)">Diff</a>

Export Accept-CH Cache

---

index.bs

fixes #159
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/160.html" title="Last updated on May 21, 2024, 9:53 AM UTC (4fd70cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/160/404398c...4fd70cb.html" title="Last updated on May 21, 2024, 9:53 AM UTC (4fd70cb)">Diff</a>

Use http-equiv not name for Delegate-CH

---

index.bs

Fixes #161
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/162.html" title="Last updated on Jun 13, 2024, 4:12 PM UTC (0b37462)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/162/11b77f0...miketaylr:0b37462.html" title="Last updated on Jun 13, 2024, 4:12 PM UTC (0b37462)">Diff</a>

Add cha-ua-form-factors to list of policy-controlled features
