index.bs
In order to run https://w3c.github.io/webappsec-feature-policy/#is-feature-enabled, HTML documents need to know about all of these new policy-controlled features for client hints
=> Extend HTML's list of policy-controlled features

index.bs
Closes #19 as well as adds the UA hints that are sent by default in implementations to the low-entropy hints table.
=> Align low entropy hints with implementations and send to all requests

index.bs
Since the responsible browsing context [died](https://github.com/whatwg/html/pull/5441/files), this PR replaces it.
/TBR @domenic
=> Replace responsible browsing context

index.bs
=> Make http-equiv Accept-CH non-persistent

index.bs
The Feature Policy spec has been renamed to Permissions Policy, and the spec has moved (in some cases, a couple of times) since the URL references here were originally written.
=> Update references to Feature Policy

index.bs
This seems to be all that is needed to spec the Viewport-Height client hint from an infrastructure point of view This is a companion to https://github.com/WICG/responsive-image-client-hints/pull/8. WDYT @yoavweiss?
=> Add Viewport-Height Client Hint Infrastructure

index.bs
Fixes a few spec inconsistencies, related to UA-CH tokens and prefixes in the Request processing algorithm.
=> Fixes #45, #46 - Fix a few consistency issues

README.md
It's no longer a thing.
PTAL @yoavweiss
=> Fixes #50 - Remove reference to UA-CH-Lifetime from explainer

reliability.md
We actually already link to them, but only embedded in the text. I've linked to the unsuffixed versions which, on tools.ietf.org, does seem to redirect to the latest one. (Though this does risk the section number links getting out of sync.)
=> Link to draft specifications in reliability.md.

index.bs
Turns out you need 4 spaces https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists
=> Fix nested list

index.bs
https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-color-scheme
FYI: @beaufortfrancois
***
<a href="https://pr-preview.s3.amazonaws.com/tomayac/client-hints-infrastructure/pull/81.html" title="Last updated on Aug 17, 2021, 9:33 AM UTC (adce497)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/81/a7ed06e...tomayac:adce497.html" title="Last updated on Aug 17, 2021, 9:33 AM UTC (adce497)">Diff</a>
=> Add `Sec-CH-Prefers-Color-Scheme`

index.bs
PTAL, @yoavweiss 
To be landed once https://github.com/WICG/ua-client-hints/pull/250 is ready to land.
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/86.html" title="Last updated on Sep 9, 2021, 9:54 PM UTC (06cc1da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/86/59100e6...miketaylr:06cc1da.html" title="Last updated on Sep 9, 2021, 9:54 PM UTC (06cc1da)">Diff</a>
=> Fixes #85 - Add Sec-CH-UA-Full-Version-List bits

index.bs
Both sections should be formatted the same
=> Make `Request processing` formatting consistent

index.bs
We need to add new client hints which should be sent, not just remove ones that shouldn't.
closes #48
closes #39
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/95.html" title="Last updated on Jan 28, 2022, 9:56 PM UTC (93ff7bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/95/ebc6ee0...93ff7bb.html" title="Last updated on Jan 28, 2022, 9:56 PM UTC (93ff7bb)">Diff</a>
=> Fix Client Hint Redirect Calculation

index.bs
The division of labor between requests and responses were unclear, and instead the document was written as though no action was taken until a document was loaded. This prevented the accept-ch cache from being updated on HTTP redirect as the response wasn't processed.
closes #42
closes #41
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/96.html" title="Last updated on Feb 1, 2022, 8:36 PM UTC (14f8cb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/96/efdef0b...14f8cb1.html" title="Last updated on Feb 1, 2022, 8:36 PM UTC (14f8cb1)">Diff</a>
=> Clarify Accept-CH cache actions

index.bs
closes #99
This change is the result of a discussion on the intent to ship thread: https://groups.google.com/a/chromium.org/g/blink-dev/c/HR7tWmewbSA/m/f4le2e8yDAAJ
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/101.html" title="Last updated on Mar 24, 2022, 7:48 PM UTC (9acd92d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/101/7ee781c...9acd92d.html" title="Last updated on Mar 24, 2022, 7:48 PM UTC (9acd92d)">Diff</a>
=> Revert Sec-CH-Save-Data to Save-Data and retain original behavior

index.bs
We need to include non-subresource requests except for sharedworkers and workers ones as those have no permissions policy.
closes #105
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/106.html" title="Last updated on Apr 20, 2022, 3:22 PM UTC (8df0d90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/106/239670d...8df0d90.html" title="Last updated on Apr 20, 2022, 3:22 PM UTC (8df0d90)">Diff</a>
=> Fix request type

index.bs
closes #108
https://bugs.chromium.org/p/chromium/issues/detail?id=1334152
This uses the iframe allow syntax (which we were already improperly referencing) and clarifies how the parsing should work based on chrome behavior.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/109.html" title="Last updated on Jun 14, 2022, 10:10 AM UTC (6132b1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/109/2bfe634...6132b1d.html" title="Last updated on Jun 14, 2022, 10:10 AM UTC (6132b1d)">Diff</a>
=> Update parsing algorithm

index.bs
Reverts WICG/client-hints-infrastructure#114
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/115.html" title="Last updated on Jun 29, 2022, 4:58 AM UTC (44034da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/115/f1a30bf...44034da.html" title="Last updated on Jun 29, 2022, 4:58 AM UTC (44034da)">Diff</a>
=> Revert "test"

index.bs
https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-reduced-motion
FYI: @tomayac
***
<a href="https://pr-preview.s3.amazonaws.com/beaufortfrancois/client-hints-infrastructure/pull/128.html" title="Last updated on Sep 15, 2022, 8:45 AM UTC (a68f30d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/128/6bd54dd...beaufortfrancois:a68f30d.html" title="Last updated on Sep 15, 2022, 8:45 AM UTC (a68f30d)">Diff</a>
=> Add `Sec-CH-Prefers-Reduced-Motion`

index.bs
PTAL @yoavweiss 
(we could also add a note to clarify this means all hints are high-entropy by default, but maybe that's obvious)
Fixes #126
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/127.html" title="Last updated on Sep 19, 2022, 1:09 PM UTC (3b2a22a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/127/63db401...miketaylr:3b2a22a.html" title="Last updated on Sep 19, 2022, 1:09 PM UTC (3b2a22a)">Diff</a>
=> Define "high-entropy client hint"

index.bs
This was missing from the list despite being defined here: https://wicg.github.io/ua-client-hints/#sec-ch-ua-wow64
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/129.html" title="Last updated on Sep 29, 2022, 4:34 PM UTC (e085471)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/129/1a90cb9...e085471.html" title="Last updated on Sep 29, 2022, 4:34 PM UTC (e085471)">Diff</a>
=> Add WoW64 UA CH to spec

index.bs
closes #130 
UA infra's point of connection with the Fetch spec is too early up the stack, and append CH needs to be called lower (after the CORS checks)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/131.html" title="Last updated on Oct 4, 2022, 2:51 PM UTC (36262bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/131/9c77cba...36262bb.html" title="Last updated on Oct 4, 2022, 2:51 PM UTC (36262bb)">Diff</a>
=> Fix fetch point of integration

index.bs
We need to specify which user-agent and fix a HTML ref
that no longer has an exported DFN.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/132.html" title="Last updated on Dec 9, 2022, 9:17 AM UTC (2d087e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/132/2846a0a...2d087e3.html" title="Last updated on Dec 9, 2022, 9:17 AM UTC (2d087e3)">Diff</a>
=> Fix Compile Issue

index.bs
Any client hints that don't start with `sec-` need to be manually listed.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/133.html" title="Last updated on Dec 13, 2022, 4:57 PM UTC (36dc5c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/133/e4b5a58...36dc5c1.html" title="Last updated on Dec 13, 2022, 4:57 PM UTC (36dc5c1)">Diff</a>
=> Update CORS forbidden headers

index.bs
As written, the cache is append only. This is incorrect as, with any Accept-CH header set, the entire cache should be overwritten with the new contents.
https://github.com/WICG/client-hints-infrastructure/issues/134#issuecomment-1355448722
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/135.html" title="Last updated on Dec 21, 2022, 9:30 PM UTC (12bb8d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/135/5f8052b...12bb8d3.html" title="Last updated on Dec 21, 2022, 9:30 PM UTC (12bb8d3)">Diff</a>
=> Fix cache logic

index.bs
This has been supported for a while in Chrome, but wasn't
previously documented. Let's fill that gap.
Closes #102
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/138.html" title="Last updated on Dec 28, 2022, 3:06 PM UTC (1c4e651)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/138/3d66949...1c4e651.html" title="Last updated on Dec 28, 2022, 3:06 PM UTC (1c4e651)">Diff</a>
=> Implement Critical-CH header

index.bs
We should allow exactly one reload and after that
prevent a second without some navigation.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/139.html" title="Last updated on Dec 29, 2022, 1:19 PM UTC (7e46460)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/139/d3ce15f...7e46460.html" title="Last updated on Dec 29, 2022, 1:19 PM UTC (7e46460)">Diff</a>
=> Prevent Critical-CH loop

index.bs
Then I can properly link to it from UA-CH:
https://github.com/WICG/ua-client-hints/blob/main/index.bs#L48
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/client-hints-infrastructure/pull/143.html" title="Last updated on Feb 9, 2023, 12:32 AM UTC (93d14e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/143/09219c0...miketaylr:93d14e9.html" title="Last updated on Feb 9, 2023, 12:32 AM UTC (93d14e9)">Diff</a>
=> Export "append client hints to request" abstract-op

index.bs
This isn't referenced in the RFC, and I didn't see one it was noted in. closes #144
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/145.html" title="Last updated on Feb 10, 2023, 3:16 PM UTC (d4f247f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/145/510827b...d4f247f.html" title="Last updated on Feb 10, 2023, 3:16 PM UTC (d4f247f)">Diff</a>
=> Correct Critical-CH definition point

index.bs
It turns out that while you can split items in an sf-list across multiple headers, you cannot include empty headers without forcing the parsing to return no items.
Verified in https://chromium-review.googlesource.com/c/chromium/src/+/4324500 as proper parsing behavior.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/148.html" title="Last updated on Mar 9, 2023, 4:22 PM UTC (3895798)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/148/a18ab02...3895798.html" title="Last updated on Mar 9, 2023, 4:22 PM UTC (3895798)">Diff</a>
=> Fix Empty Header Handling

index.bs
This should be a no-op logic wise, just cleaning for clarity.
closes #151
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/152.html" title="Last updated on Apr 26, 2023, 11:42 AM UTC (275d17f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/152/a163e1d...275d17f.html" title="Last updated on Apr 26, 2023, 11:42 AM UTC (275d17f)">Diff</a>
=> Simplify `append client hints to request`'s Step 6.1

index.bs
This is needed for https://github.com/w3c/navigation-timing/pull/188/.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/153.html" title="Last updated on Jun 7, 2023, 1:27 PM UTC (edb2997)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/153/96a82df...edb2997.html" title="Last updated on Jun 7, 2023, 1:27 PM UTC (edb2997)">Diff</a>
=> Update Critical-CH restart time in navigation params

index.bs
Let's be sure the spec references the Clear-Site-Data support for cache clearing.
https://github.com/WICG/client-hints-infrastructure/issues/155
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/pull/157.html" title="Last updated on Jul 14, 2023, 12:18 PM UTC (eb0afa1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/client-hints-infrastructure/157/c9d66e8...eb0afa1.html" title="Last updated on Jul 14, 2023, 12:18 PM UTC (eb0afa1)">Diff</a>
=> Add Clear-Site-Data note
